"use client";
import { execute } from "@/actions/client";
import { MagicboxContext } from "@/app/koksmat/magicbox-context";
import { useContext, useState } from "react";

// import React, { useEffect, useState } from "react";
export function useDatabaseMixSqlqueryItemUpdate() {
  /* ---------------------- Update Record ----------------------
* This code is generated by Koksmat Studio. You can modify it as you like.
* The code is generated based on the database and table you have selected.
* No warranty is given for the code.
*
* Suggest that you use the refactor function and move the code to a separate file,
* then move that file to a folder where you keep your custom hooks.
 
* ----------------------------------------------------------
*/
  const magicbox = useContext(MagicboxContext);
  const [error, seterror] = useState("");
  const [loading, setloading] = useState(false);
  const [result, setresult] = useState<any>();
  const update = async (record: any) => {
    setloading(true);
    seterror("");
    const result = await execute(

      magicbox.authtoken, // <-- this is the authentication token containing the user's credentials - the upn will be used as "actor" name
      "works", // <-- this is a reference to a record in the connections table in the mix database
      "magic-mix.app", // <-- this is the service name processing the request
      "update_sqlquery", // <-- this is the name of the procedure in the database pointed to by the connection
      record // <-- this is the data to be sent to the procedure
    );
    setloading(false);
    if (result.hasError) {
      seterror(result.errorMessage ?? "Unknown error");
    }
    setresult(result);


  };
  return { update, error, loading, result };
}
