/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2sCePKazBr9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"

export function AccessMatrix() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Access Matrix</CardTitle>
        <CardDescription>Manage access permissions for your team members.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b bg-muted">
                <th className="p-4 font-medium">Access Holder</th>
                <th className="p-4 font-medium">Owner</th>
                <th className="p-4 font-medium">Admin</th>
                <th className="p-4 font-medium">Editor</th>
                <th className="p-4 font-medium">Viewer</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b">
                <td className="p-4 font-medium">John Doe</td>
                <td className="p-4">
                  <Checkbox id="john-owner" />
                </td>
                <td className="p-4">
                  <Checkbox id="john-admin" />
                </td>
                <td className="p-4">
                  <Checkbox id="john-editor" />
                </td>
                <td className="p-4">
                  <Checkbox id="john-viewer" />
                </td>
              </tr>
              <tr className="border-b">
                <td className="p-4 font-medium">Jane Smith</td>
                <td className="p-4">
                  <Checkbox id="jane-owner" />
                </td>
                <td className="p-4">
                  <Checkbox id="jane-admin" />
                </td>
                <td className="p-4">
                  <Checkbox id="jane-editor" />
                </td>
                <td className="p-4">
                  <Checkbox id="jane-viewer" />
                </td>
              </tr>
              <tr className="border-b">
                <td className="p-4 font-medium">Bob Johnson</td>
                <td className="p-4">
                  <Checkbox id="bob-owner" />
                </td>
                <td className="p-4">
                  <Checkbox id="bob-admin" />
                </td>
                <td className="p-4">
                  <Checkbox id="bob-editor" />
                </td>
                <td className="p-4">
                  <Checkbox id="bob-viewer" />
                </td>
              </tr>
              <tr className="border-b">
                <td className="p-4 font-medium">Sarah Lee</td>
                <td className="p-4">
                  <Checkbox id="sarah-owner" />
                </td>
                <td className="p-4">
                  <Checkbox id="sarah-admin" />
                </td>
                <td className="p-4">
                  <Checkbox id="sarah-editor" />
                </td>
                <td className="p-4">
                  <Checkbox id="sarah-viewer" />
                </td>
              </tr>
              <tr className="border-b">
                <td className="p-4 font-medium">Michael Chen</td>
                <td className="p-4">
                  <Checkbox id="michael-owner" />
                </td>
                <td className="p-4">
                  <Checkbox id="michael-admin" />
                </td>
                <td className="p-4">
                  <Checkbox id="michael-editor" />
                </td>
                <td className="p-4">
                  <Checkbox id="michael-viewer" />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  )
}
