/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eJHEH0Bq3hZ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from "@/components/ui/card";

export interface DatabaseProps {
  id: number;
  title: string;
  slug: string;
  description: string;
}

export function DashboardDatabases(props: { databases: DatabaseProps[] }) {
  return (
    <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
      <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        {props.databases.map((database) => (
          <Card key={database.id}>
            <CardHeader className="flex flex-col items-start gap-2">
              <DatabaseIcon className="h-6 w-6 text-muted-foreground" />
              <CardTitle>{database.title}</CardTitle>
              <CardDescription>{database.description}</CardDescription>
            </CardHeader>
            <CardFooter>
              <Link
                href={"/studio/database/" + database.slug}
                className="text-primary"
                prefetch={false}
              >
                Open Database
              </Link>
            </CardFooter>
          </Card>
        ))}
      </div>
    </main>
  );
}

function DatabaseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  );
}
