/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/chTSXyQDrk5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function HeroIntroduceDatabaseLogic() {
  return (
    <div className="w-full">
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-primary to-primary/80">
        <div className="container px-4 md:px-6 text-center text-primary-foreground">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Seamless Database Integration</h1>
          <p className="mx-auto max-w-[700px] mt-4 text-lg md:text-xl">
            Unlock the power of your data with our intuitive database integration tools. Streamline your application
            development and focus on building great experiences.
          </p>
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary-foreground px-8 text-sm font-medium text-primary shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 mt-6"
            prefetch={false}
          >
            Get Started
          </Link>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Instruction</div>
              <h2 className="text-2xl font-bold">Step-by-Step Guidance</h2>
              <p className="text-muted-foreground">
                Follow our detailed instructions to seamlessly integrate your database with your application. We provide
                easy-to-copy code snippets to get you started.
              </p>
              <div className="bg-muted rounded-lg p-4">
                <pre className="text-sm text-muted-foreground">{`const { data } = await fetch('/api/database')
                  .then(res => res.json());

                  // Use the data in your application`}</pre>
              </div>
            </div>
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">AI Prompts</div>
              <h2 className="text-2xl font-bold">AI-Powered Suggestions</h2>
              <p className="text-muted-foreground">
                Leverage our AI-generated prompts to quickly add database-related functionality to your application.
                Explore a variety of use cases and customize them to your needs.
              </p>
              <div className="bg-muted rounded-lg p-4">
                <pre className="text-sm text-muted-foreground">{`// Generate a stored procedure to fetch user data
                  const prompt = "Create a stored procedure to fetch all user data from the database, including name, email, and registration date.";
                  const response = await openai.createCompletion(prompt);
                  console.log(response.data.choices[0].text);`}</pre>
              </div>
            </div>
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Source Code</div>
              <h2 className="text-2xl font-bold">Stored Procedure Source</h2>
              <p className="text-muted-foreground">
                Explore the underlying SQL code for the stored procedures used in your application. Understand the logic
                and customize it to fit your specific requirements.
              </p>
              <div className="bg-muted rounded-lg p-4">
                <pre className="text-sm text-muted-foreground">{`CREATE PROCEDURE GetAllUsers
                  AS
                  BEGIN
                    SELECT 
                      UserID, 
                      FirstName, 
                      LastName, 
                      Email, 
                      RegistrationDate
                    FROM Users
                  END`}</pre>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
