/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i3kzKQWx0Aa
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { string } from "zod";
export interface KitchenDetails {
  name: string;
  description: string;
}
export interface KitchenOverviewProps {
  details?: KitchenDetails;
}
export function KitchenOverview(props: KitchenOverviewProps) {
  return (
    <div className="w-full mx-auto py-12 md:py-20 lg:py-24">
      <div className="px-4 md:px-6">
        <div className="grid gap-8 md:grid-cols-[1fr_300px] lg:grid-cols-[1fr_350px] xl:grid-cols-[1fr_400px]">
          <div>
            <div className="space-y-6">
              <div>
                <div className="flex items-center justify-between">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                    Project Overview
                  </h1>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    View Project
                  </Link>
                </div>
                <p className="mt-2 text-muted-foreground md:text-xl">
                  Get a comprehensive view of your project&apos;s progress.
                </p>
              </div>
              <div>
                <h2 className="text-xl font-bold">Active Branch</h2>
                <div className="mt-2 rounded-lg border bg-background p-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <GitBranchIcon className="h-5 w-5 text-muted-foreground" />
                      <div className="font-medium">main</div>
                    </div>
                    <Badge
                      variant="secondary"
                      className="bg-primary/10 text-primary"
                    >
                      Active
                    </Badge>
                  </div>
                  <div className="mt-2 text-muted-foreground">
                    Last updated 2 days ago
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-xl font-bold">Latest Releases</h2>
                <div className="mt-2 space-y-2">
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <TagIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">v1.2.0</div>
                          <div className="text-muted-foreground">
                            Released 1 week ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <TagIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">v1.1.0</div>
                          <div className="text-muted-foreground">
                            Released 2 weeks ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <TagIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">v1.0.0</div>
                          <div className="text-muted-foreground">
                            Released 1 month ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-xl font-bold">Latest Check-ins</h2>
                <div className="mt-2 space-y-2">
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <GitCommitVerticalIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">
                            Implement new feature #123
                          </div>
                          <div className="text-muted-foreground">
                            Committed 2 days ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <GitCommitVerticalIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">
                            Fix bug in login flow #122
                          </div>
                          <div className="text-muted-foreground">
                            Committed 3 days ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <GitCommitVerticalIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">
                            Refactor codebase for performance #121
                          </div>
                          <div className="text-muted-foreground">
                            Committed 1 week ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-xl font-bold">Latest Issues</h2>
                <div className="mt-2 space-y-2">
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <BugIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">
                            Unexpected error in login flow
                          </div>
                          <div className="text-muted-foreground">
                            Reported 2 days ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <FlagIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">
                            Implement new dashboard design
                          </div>
                          <div className="text-muted-foreground">
                            Reported 3 days ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                  <div className="rounded-lg border bg-background p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <TimerIcon className="h-5 w-5 text-muted-foreground" />
                        <div>
                          <div className="font-medium">
                            Improve accessibility for screen readers
                          </div>
                          <div className="text-muted-foreground">
                            Reported 1 week ago
                          </div>
                        </div>
                      </div>
                      <Link
                        href="#"
                        className="inline-flex h-8 items-center justify-center rounded-md bg-primary/10 px-3 text-sm font-medium text-primary transition-colors hover:bg-primary/20 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                        prefetch={false}
                      >
                        View
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="rounded-lg border bg-background p-6">
            <h2 className="text-xl font-bold">Project Navigation</h2>
            <div className="mt-4 space-y-2">
              <div className="flex items-center gap-2">
                <FolderIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">src</div>
              </div>
              <div className="flex items-center gap-2">
                <FolderIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">components</div>
              </div>
              <div className="flex items-center gap-2">
                <FileIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">Header.tsx</div>
              </div>
              <div className="flex items-center gap-2">
                <FileIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">Footer.tsx</div>
              </div>
              <div className="flex items-center gap-2">
                <FolderIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">pages</div>
              </div>
              <div className="flex items-center gap-2">
                <FileIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">index.tsx</div>
              </div>
              <div className="flex items-center gap-2">
                <FileIcon className="h-5 w-5 text-muted-foreground" />
                <div className="font-medium">about.tsx</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function BugIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 2 1.88 1.88" />
      <path d="M14.12 3.88 16 2" />
      <path d="M9 7.13v-1a3.003 3.003 0 1 1 6 0v1" />
      <path d="M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6" />
      <path d="M12 20v-9" />
      <path d="M6.53 9C4.6 8.8 3 7.1 3 5" />
      <path d="M6 13H2" />
      <path d="M3 21c0-2.1 1.7-3.9 3.8-4" />
      <path d="M20.97 5c0 2.1-1.6 3.8-3.5 4" />
      <path d="M22 13h-4" />
      <path d="M17.2 17c2.1.1 3.8 1.9 3.8 4" />
    </svg>
  );
}

function FileIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  );
}

function FlagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function FolderIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  );
}

function GitBranchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="6" x2="6" y1="3" y2="15" />
      <circle cx="18" cy="6" r="3" />
      <circle cx="6" cy="18" r="3" />
      <path d="M18 9a9 9 0 0 1-9 9" />
    </svg>
  );
}

function GitCommitVerticalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3v6" />
      <circle cx="12" cy="12" r="3" />
      <path d="M12 15v6" />
    </svg>
  );
}

function TagIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z" />
      <circle cx="7.5" cy="7.5" r=".5" fill="currentColor" />
    </svg>
  );
}

function TimerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="10" x2="14" y1="2" y2="2" />
      <line x1="12" x2="15" y1="14" y2="11" />
      <circle cx="12" cy="14" r="8" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
