/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wart4omThwI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"

export function PermissionManagementPage() {
  return (
    <div className="flex flex-col gap-8">
      <div className="flex flex-col md:flex-row items-start justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="grid gap-1">
            <h1 className="text-2xl font-bold tracking-tight">Permission Matrix</h1>
            <p className="text-muted-foreground">Manage permissions for roles and endpoints.</p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="icon">
              <BoxSelectIcon className="w-4 h-4" />
              <span className="sr-only">Select</span>
            </Button>
            <Button variant="outline" size="icon">
              <PlusIcon className="w-4 h-4" />
              <span className="sr-only">Add</span>
            </Button>
            <Button variant="outline" size="icon">
              <TrashIcon className="w-4 h-4" />
              <span className="sr-only">Delete</span>
            </Button>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <div className="relative">
            <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input type="search" placeholder="Search..." className="pl-8" />
          </div>
          <Button size="sm">Add Permission</Button>
        </div>
      </div>
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Endpoint</TableHead>
              <TableHead>Admin</TableHead>
              <TableHead>Manager</TableHead>
              <TableHead>Editor</TableHead>
              <TableHead>Viewer</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>/api/users</TableCell>
              <TableCell>
                <Badge variant="secondary">Grant</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="outline">Deny</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="destructive">Veto</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="outline">Deny</Badge>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>/api/posts</TableCell>
              <TableCell>
                <Badge variant="secondary">Grant</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="secondary">Grant</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="secondary">Grant</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="outline">Deny</Badge>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>/api/settings</TableCell>
              <TableCell>
                <Badge variant="secondary">Grant</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="outline">Deny</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="destructive">Veto</Badge>
              </TableCell>
              <TableCell>
                <Badge variant="destructive">Veto</Badge>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
      <Dialog>
        <DialogTrigger asChild>
          <Button size="sm">Add Permission</Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Add/Modify Permission</DialogTitle>
            <DialogDescription>Configure permissions for roles and endpoints.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="role" className="text-right">
                Role
              </Label>
              <Select id="role" defaultValue="admin" className="col-span-3">
                <SelectTrigger>
                  <SelectValue placeholder="Select a role" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="admin">Admin</SelectItem>
                  <SelectItem value="manager">Manager</SelectItem>
                  <SelectItem value="editor">Editor</SelectItem>
                  <SelectItem value="viewer">Viewer</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="endpoint" className="text-right">
                Endpoint
              </Label>
              <Input id="endpoint" placeholder="/api/example" className="col-span-3" />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="permission" className="text-right">
                Permission
              </Label>
              <div className="col-span-3 flex items-center gap-4">
                <Label htmlFor="grant" className="flex items-center gap-2">
                  <RadioGroup>
                    <RadioGroupItem id="grant" value="grant" defaultChecked />
                    Grant
                  </RadioGroup>
                </Label>
                <Label htmlFor="deny" className="flex items-center gap-2">
                  <RadioGroup>
                    <RadioGroupItem id="deny" value="deny" />
                    Deny
                  </RadioGroup>
                </Label>
                <Label htmlFor="veto" className="flex items-center gap-2">
                  <RadioGroup>
                    <RadioGroupItem id="veto" value="veto" />
                    Veto
                  </RadioGroup>
                </Label>
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button type="submit">Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

function BoxSelectIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 3a2 2 0 0 0-2 2" />
      <path d="M19 3a2 2 0 0 1 2 2" />
      <path d="M21 19a2 2 0 0 1-2 2" />
      <path d="M5 21a2 2 0 0 1-2-2" />
      <path d="M9 3h1" />
      <path d="M9 21h1" />
      <path d="M14 3h1" />
      <path d="M14 21h1" />
      <path d="M3 9v1" />
      <path d="M21 9v1" />
      <path d="M3 14v1" />
      <path d="M21 14v1" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
