/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ORPy5r6Df9g
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function ResourceRoleMatrix() {
  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Resource Matrix</CardTitle>
        <CardDescription>Visualize resource permissions across roles.</CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead />
              <TableHead>Admin</TableHead>
              <TableHead>Editor</TableHead>
              <TableHead>Viewer</TableHead>
              <TableHead>Guest</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium">Create new projects</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Delete projects</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Update project settings</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">View project analytics</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Access project logs</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Manage team members</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">Deploy to production</TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <CheckIcon className="w-5 h-5 text-green-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
              <TableCell>
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function DoorClosedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 20V6a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v14" />
      <path d="M2 20h20" />
      <path d="M14 12v.01" />
    </svg>
  )
}
