/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MvNk4l8vH7o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function ResultingPermissionPage() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12">
      <div className="flex flex-col gap-8">
        <div>
          <h1 className="text-3xl font-bold">Effective Permissions</h1>
          <p className="text-muted-foreground">View the combined permissions for a selected user or role.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <Card>
            <CardHeader>
              <CardTitle>User Permissions</CardTitle>
              <CardDescription>View the effective permissions for a selected user.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between mb-4">
                <Label htmlFor="user-select">Select User</Label>
                <Select id="user-select" defaultValue="john@example.com">
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select User" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="john@example.com">John Doe</SelectItem>
                    <SelectItem value="jane@example.com">Jane Smith</SelectItem>
                    <SelectItem value="bob@example.com">Bob Johnson</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Endpoint</TableHead>
                    <TableHead>Permissions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>users:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>users:write</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>products:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>orders:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>settings:write</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Role Permissions</CardTitle>
              <CardDescription>View the permissions for a selected role.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between mb-4">
                <Label htmlFor="role-select">Select Role</Label>
                <Select id="role-select" defaultValue="admin">
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select Role" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="admin">Admin</SelectItem>
                    <SelectItem value="manager">Manager</SelectItem>
                    <SelectItem value="user">User</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Endpoint</TableHead>
                    <TableHead>Permissions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>users:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>users:write</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>products:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>products:write</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>orders:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>orders:write</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>settings:read</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Read</Badge>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>settings:write</TableCell>
                    <TableCell>
                      <Badge variant="secondary">Write</Badge>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
