"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9AdUfQ9urZK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";
import { Collapsible } from "@/components/ui/collapsible";

export function SideBySide(props: { left: any; right: any }) {
  return (
    <div className="flex h-full w-full overflow-hidden rounded-lg border ">
      <ResizablePanelGroup direction="horizontal" className="w-full">
        <ResizablePanel defaultSize={40}>
          <div className="flex h-full flex-col justify-between bg-background p-6">
            <div>
              <h3 className="text-2xl font-bold">Left Panel</h3>
            </div>
            {props.left}
          </div>
        </ResizablePanel>
        <ResizableHandle withHandle />
        <ResizablePanel defaultSize={60}>
          <div className="flex h-full flex-col justify-between bg-background p-6">
            <div>
              <h3 className="text-2xl font-bold">Right Panel</h3>
              <p className="text-muted-foreground">
                This is the right panel with a collapsible option.
              </p>
            </div>
            {props.right}
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
}
