"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vFndfg4IeKP
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useSQLSelect3 } from "@/app/koksmat/usesqlselect3";
import { useEffect, useState } from "react";
import { APPNAME } from "@/app/global";
import { extractAndParseJson } from "@/lib/tsql-extract";
import { z } from "zod";
import { resolveRefs } from "json-refs";
import * as parserTypeScript from "prettier/parser-typescript";
import * as prettier from "prettier/standalone";
import { jsonSchemaToZod } from "json-schema-to-zod";
import InterfaceBuilder from "./interface-builder";
import { InterfaceViewer } from "./interface-viewer";

export interface Root {
  Result: Result[];
}

export interface Result {
  procedure_info: ProcedureInfo;
}

export interface ProcedureInfo {
  procedure_name: string;
  comment: string;
  language: string;
  source_code: string;
  dependencies: any[];
}

export function StoredProcedurePage(props: {
  database: string;
  procedure: string;
}) {
  const { database, procedure } = props;
  const sql = `
WITH proc_source AS (
    SELECT
        p.oid AS procedure_oid,
        p.proname AS procedure_name,
        l.lanname AS language,
        pg_get_functiondef(p.oid) AS source_code,
        d.description AS comment
    FROM
        pg_proc p
    JOIN
        pg_language l ON p.prolang = l.oid
    LEFT JOIN
        pg_description d ON p.oid = d.objoid
    WHERE
        p.proname = '${procedure}'
),
func_deps AS (
    SELECT
        d.refobjid AS table_oid,
        d.objid AS procedure_oid,
        c2.relname AS table_name
    FROM
        pg_depend d
    JOIN
        pg_proc p ON d.objid = p.oid
    JOIN
        pg_class c2 ON d.refobjid = c2.oid
    WHERE
        p.proname = '${procedure}'
        AND c2.relkind = 'r'
)
SELECT json_build_object(
    'procedure_name', ps.procedure_name,
    'language', ps.language,
    'source_code', ps.source_code,
    'comment', ps.comment,
    'dependencies', COALESCE(json_agg(fd.table_name) FILTER (WHERE fd.table_name IS NOT NULL), '[]'::json)
) AS procedure_info
FROM
    proc_source ps
LEFT JOIN
    func_deps fd ON ps.procedure_oid = fd.procedure_oid
GROUP BY
    ps.procedure_name, ps.language, ps.source_code, ps.comment

  `;
  const query = useSQLSelect3<Result>(database, sql);
  const [procedureInfo, setprocedureInfo] = useState<ProcedureInfo>();
  const [jsonSchema, setjsonSchema] = useState<any | null>();
  const [zodSchema, setzodSchema] = useState<any | null>();
  useEffect(() => {
    if (query && query.dataset && query.dataset.length > 0) {
      const procedure = query.dataset[0].procedure_info;
      setprocedureInfo(procedure);
      const metadata = extractAndParseJson(procedure.source_code);
      if (metadata) {
        try {
          setjsonSchema(metadata);
          const txtcode = jsonSchemaToZod(metadata);

          // const code = prettier.format(txtcode, {
          //   parser: "typescript",
          //   plugins: [parserTypeScript],
          // });
          //setzodSchema(JSON.parse(zodSchema));
          setzodSchema(txtcode);
        } catch (error) {
          setzodSchema(error);
        }
      }
      //setmetadata(metadata);
    }
  }, [query, database, procedure]);

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-40 border-b bg-background px-4 py-3 shadow-sm sm:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="#" className="flex items-center gap-2" prefetch={false}>
              <DatabaseIcon className="h-6 w-6" />
              <span className="font-bold">{procedure}</span>
            </Link>
            <span className="text-muted-foreground">Procedure Name</span>
          </div>
          <div className="flex items-center gap-4">
            <Button variant="outline">
              <FilePenIcon className="mr-2 h-4 w-4" />
              Edit
            </Button>
            <Button>
              <DownloadIcon className="mr-2 h-4 w-4" />
              Download
            </Button>
          </div>
        </div>
      </header>
      <div className="container mx-auto grid grid-cols-[200px_1fr] gap-8 py-8 sm:px-6">
        <nav className="sticky top-20 space-y-2">
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground"
            prefetch={false}
          >
            <DatabaseIcon className="h-4 w-4" />
            Source Code
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground"
            prefetch={false}
          >
            <DatabaseIcon className="h-4 w-4" />
            Table Dependencies
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-muted hover:text-foreground"
            prefetch={false}
          >
            <DatabaseIcon className="h-4 w-4" />
            Code Generator
          </Link>
        </nav>
        <div className="space-y-8">
          <section>
            <h2 className="mb-4 text-2xl font-bold">Integration Options</h2>
            {/* <div>
              <h3 className="mb-2 text-lg font-medium">ZOD definition</h3>
              <pre className="text-wrap">{zodSchema}</pre>
            </div>
            <div>
              <h3 className="mb-2 text-lg font-medium">JSON schema</h3>
              <pre className="text-wrap">
                {JSON.stringify(jsonSchema, null, 2)}
              </pre>
            </div> */}
            <InterfaceViewer />
            <div>
              <h3 className="mb-2 text-lg font-medium">TypeScript Interface</h3>
              <InterfaceBuilder
                schema={JSON.stringify(jsonSchema, null, 2)}
                typeName={"Koksmat"}
              />
            </div>
          </section>
          <section>
            <h2 className="mb-4 text-2xl font-bold">Procedure Details</h2>
            <div className="grid gap-8">
              <div>
                <h3 className="mb-2 text-lg font-medium">Description</h3>
                <pre>{procedureInfo?.comment}</pre>
              </div>
              <div>
                <h3 className="mb-2 text-lg font-medium">Table Dependencies</h3>
                <ul className="space-y-1">
                  {procedureInfo?.dependencies.map((dep, index) => (
                    <li key={index}>
                      <Link
                        href={
                          "/" +
                          APPNAME +
                          "/database/" +
                          database +
                          "/table/" +
                          dep
                        }
                        className="text-primary hover:underline"
                        prefetch={false}
                      >
                        {dep}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="mb-2 text-lg font-medium">Source Code</h3>
                <pre className="rounded-md bg-muted p-4 text-sm">
                  <code>{procedureInfo?.source_code}</code>
                </pre>
              </div>
            </div>
          </section>
          <section>
            <div className="grid gap-4">
              <div>
                <h3 className="mb-2 text-lg font-medium">REST POST</h3>
                <pre className="rounded-md bg-muted p-4 text-sm">
                  <code>{`
const response = await fetch('/api/procedures/GetOrdersByUser', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({ UserId: 123 }),
});

const data = await response.json();
console.log(data);
                    `}</code>
                </pre>
              </div>
            </div>
          </section>
        </div>
      </div>
      <footer className="mt-auto border-t bg-background px-4 py-4 shadow-sm sm:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            &copy; 2024 Acme Inc. All rights reserved.
          </p>
          <div className="flex items-center gap-4">
            <Link
              href="#"
              className="text-sm text-muted-foreground hover:text-foreground"
              prefetch={false}
            >
              Terms of Service
            </Link>
            <Link
              href="#"
              className="text-sm text-muted-foreground hover:text-foreground"
              prefetch={false}
            >
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function DatabaseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  );
}

function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  );
}

function FilePenIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  );
}
